apiVersion: v1
kind: Service
metadata:
  name: vehicle-sales-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: vehicle-sales-service

